version: "3.9"

services:
  mongo_database:
    container_name: mongo_db
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=test
    ports:
      - '27017:27017'
    restart: always

  postgres_database:
    container_name: postgresDB
    image: postgres:latest
    environment:
      POSTGRES_DB: pizzeria_db
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
    ports:
      - '5432:5432'
    restart: always

  eureka:
    container_name: eureka
    build: eureka-Service/
    ports:
      - '8761:8761'

  rabbitMQ:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  web:
    container_name: main
    build: primary-Service/
    ports:
      - '8080:8080'
      - '5005:5005'
    restart: always
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    depends_on:
      - postgres_database
      - rabbitMQ
      - eureka


  mongo_service:
    container_name: mongo_service
    build: mongo-Service/
    ports:
      - '8081:8081'
      - '5006:5006'
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006
    depends_on:
      - eureka

  user:
    container_name: user
    build: user-Service/
    ports:
      - '8082:8082'
      - '5007:5007'
    restart: always
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007
    depends_on:
      - postgres_database
      - rabbitMQ
      - eureka

  dish_service:
    container_name: dish_service
    build: dish-service/
    ports:
      - '8083:8083'
      - '5008:5008'
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5008
    depends_on:
      - postgres_database
      - eureka
      - rabbitMQ

  addons_service:
    container_name: addon_service
    build: addon-Service/
    ports:
      - '8084:8084'
      - '5009:5009'
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5009
    depends_on:
      - postgres_database
      - eureka
      - rabbitMQ

  ingredient_service:
    container_name: ingredient_service
    build: ingredients-Service/
    ports:
      - '8085:8085'
      - '5010:5010'
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5010
    depends_on:
      - postgres_database
      - eureka
      - rabbitMQ

  role_service:
    container_name: role_service
    build: role-Service/
    ports:
      - '8086:8086'
      - '5011:5011'
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5011
    depends_on:
      - postgres_database
      - eureka
      - rabbitMQ

  dishitem_service:
    container_name: dishitem_service
    build: dishitem-Service/
    ports:
      - '8087:8087'
      - '5012:5012'
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5012
    depends_on:
      - postgres_database
      - eureka
      - rabbitMQ

  cart_service:
    container_name: cart_service
    build: cart-Service/
    ports:
      - '8088:8088'
      - '5013:5013'
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5013
    depends_on:
      - postgres_database
      - eureka
      - rabbitMQ

  order_service:
    container_name: order_service
    build: order-Service/
    ports:
      - '8089:8089'
      - '5014:5014'
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5014
    depends_on:
      - postgres_database
      - eureka
      - rabbitMQ