version: "3.9"

services:
  mongo_database:
    container_name: mongo_db
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=test
    ports:
      - '27017:27017'
    restart: always

  postgres_database:
    container_name: postgresDB
    image: postgres:latest
    environment:
      POSTGRES_DB: pizzeria_db
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
    ports:
      - '5432:5432'
    restart: always

  mongo_service:
    container_name: mongo_service
    build: mongo-Service/
    ports:
      - '8081:8081'
      - '5006:5006'
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006

  web:
    container_name: main
    build: primary-Service/
    ports:
      - '8080:8080'
      - '5005:5005'
    restart: always
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    depends_on:
      - postgres_database
